" All system-wide defaults are set in $VIMRUNTIME/debian.vim and sourced by
" the call to :runtime you can find below.  If you wish to change any of those
" settings, you should do it in this file (/etc/vim/vimrc), since debian.vim
" will be overwritten everytime an upgrade of the vim packages is performed.
" It is recommended to make changes after sourcing debian.vim since it alters
" the value of the 'compatible' option.
" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages available in Debian.
runtime! debian.vim
"execute pathogen#infect()
"""""""""""""""""""""""""""""""""""""""""""""""""""""""
"""""  White spaces (Project settings) 
"""""""""""""""""""""""""""""""""""""""""""""""""""""""
set tabstop=2       " The width of a TAB is set to 4. 
                    " Still it is a \t. It is just that 
                    " Vim will interpret it to be having 
                    " a width of 4. 
set shiftwidth=2    " Indents will have a width of 4 
set softtabstop=2   " Sets the number of columns for a TAB 
set expandtab       " Expand TABs to spaces
set hlsearch        " highligh searched text string
" Set the current path of the buffer as the search path
nmap <F2> :lcd %:p:h<CR> 
" Set the current path to the buffer that is open and then search for the
" string 
nmap <F3> <F2>"zyiw:exec "vim ".@z." ** %"<CR>
" Open the next buffer
nmap <F4> :cn<CR>
" Open the last buffer
nmap <S-F4> :cN<CR>
"""""""""""""""""""""""""""""""""""""""""""""""""""""""
"""""   NERDTree
"""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Commands to start some plugins automatically
" autocmd vimenter * NERDTree
" autocmd StdinReadPre * let s:std_in=1
" autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
" Keyboard mapping
" map :NT :NERDTree
map <C-n> :NERDTree<CR>
" Keyboard mapping to sync the NERTTree structure to show the buffer that is
" open at the moment
map <C-t><C-f> :NERDTreeFind<CR>
let NERDTreeShowBookmarks=1
